# Compiler
set(CMAKE_C_COMPILER /usr/lib/ccache/clang)
set(CMAKE_CXX_COMPILER /usr/lib/ccache/clang++)
set(CMAKE_Fortran_COMPILER /usr/bin/gfortran)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")

set(CMAKE_CUDA_COMPILER /usr/local/cuda/bin/nvcc)
set(CMAKE_CUDA_COMPILER_LAUNCHER /usr/bin/ccache)
set(CMAKE_CXX_FLAGS_INIT "-DDISABLE_CUSPARSE_DEPRECATED=1")
set(CMAKE_CUDA_FLAGS_INIT "-DDISABLE_CUSPARSE_DEPRECATED=1")

# CMake settings
set(BUILD_SHARED_LIBS OFF)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS 1 CACHE BOOL "" FORCE)

# Python settings
set(pybind11_DIR /python_env/lib/python3.12/site-packages/pybind11/share/cmake/pybind11)

# OPM settings
set(USE_MPI ON CACHE BOOL "" FORCE)
set(USE_DAMARIS_LIB ON CACHE BOOL "" FORCE)
set(INSTALL_BENCHMARKS ON CACHE BOOL "" FORCE)
set(BUILD_FLOW_FLOAT_VARIANTS ON CACHE BOOL "" FORCE)
set(SIBLING_SEARCH OFF CACHE BOOL "" FORCE)
set(WITH_NDEBUG OFF CACHE BOOL "" FORCE)
set(OPM_ENABLE_PYTHON ON CACHE BOOL "" FORCE)
set(OPM_ENABLE_EMBEDDED_PYTHON ON CACHE BOOL "" FORCE)
set(OPM_USE_BUILD_TIMESTAMP OFF CACHE BOOL "" FORCE)
set(OPM_INSTALL_PYTHON ON CACHE BOOL "" FORCE)
set(USE_HYPRE ON CACHE BOOL "" FORCE)
set(USE_AMGX ON CACHE BOOL "" FORCE)

# CUDA settings
set(CMAKE_CUDA_ARCHITECTURES 80)
list(APPEND CMAKE_PREFIX_PATH /hypre/cuda)

# Disable packages
set(CMAKE_DISABLE_FIND_PACKAGE_Doxygen ON)
set(CMAKE_DISABLE_FIND_PACKAGE_dune-fem ON)
set(CMAKE_DISABLE_FIND_PACKAGE_dune-polygongrid ON)
set(CMAKE_DISABLE_FIND_PACKAGE_QuadMath ON)
set(CMAKE_DISABLE_FIND_PACKAGE_rocalution ON)
set(CMAKE_DISABLE_FIND_PACKAGE_rocblas ON)
set(CMAKE_DISABLE_FIND_PACKAGE_rocsparse ON)
set(CMAKE_DISABLE_FIND_PACKAGE_Tracy ON)
set(CMAKE_DISABLE_FIND_PACKAGE_Valgrind ON)

# Disable opm-tests as regression tests fail due to host code being built by clang
set(OPM_TESTS_ROOT /nonexistent)
