# Compiler
set(CMAKE_C_COMPILER /usr/lib/ccache/gcc)
set(CMAKE_CXX_COMPILER /usr/lib/ccache/g++)

# CMake settings
set(BUILD_SHARED_LIBS OFF)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY ON)

# OPM settings
set(USE_MPI ON CACHE BOOL "" FORCE)
set(SIBLING_SEARCH OFF CACHE BOOL "" FORCE)
set(WITH_NDEBUG OFF CACHE BOOL "" FORCE)
set(OPM_ENABLE_PYTHON OFF CACHE BOOL "" FORCE)
set(OPM_ENABLE_EMBEDDED_PYTHON OFF CACHE BOOL "" FORCE)
set(OPM_INSTALL_PYTHON OFF CACHE BOOL "" FORCE)
set(OPM_USE_BUILD_TIMESTAMP OFF CACHE BOOL "" FORCE)
set(USE_OPM_COMMON OFF CACHE BOOL "" FORCE)

# Disable packages
set(CMAKE_DISABLE_FIND_PACKAGE_Doxygen ON)
set(CMAKE_DISABLE_FIND_PACKAGE_dune-polygongrid ON)
set(CMAKE_DISABLE_FIND_PACKAGE_Tracy ON)
set(CMAKE_DISABLE_FIND_PACKAGE_Valgrind ON)
