# Compiler
set(CMAKE_C_COMPILER /usr/lib/ccache/gcc)
set(CMAKE_CXX_COMPILER /usr/lib/ccache/g++)
set(CMAKE_Fortran_COMPILER /usr/bin/gfortran)
set(CMAKE_CXX_FLAGS_INIT "-fuse-ld=mold")

# CMake settings
set(BUILD_SHARED_LIBS OFF)
set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY ON)

# Python settings
set(pybind11_DIR /python_env/lib/python3.12/site-packages/pybind11/share/cmake/pybind11)

# OPM settings
set(USE_MPI OFF CACHE BOOL "" FORCE)
set(USE_DAMARIS_LIB OFF CACHE BOOL "" FORCE)
set(INSTALL_BENCHMARKS ON CACHE BOOL "" FORCE)
set(BUILD_FLOW_FLOAT_VARIANTS ON CACHE BOOL "" FORCE)
set(SIBLING_SEARCH OFF CACHE BOOL "" FORCE)
set(USE_GPU_BRIDGE OFF CACHE BOOL "")
set(WITH_NDEBUG OFF CACHE BOOL "" FORCE)
set(OPM_ENABLE_PYTHON ON CACHE BOOL "" FORCE)
set(OPM_ENABLE_EMBEDDED_PYTHON ON CACHE BOOL "" FORCE)
set(OPM_INSTALL_PYTHON ON CACHE BOOL "" FORCE)
set(OPM_USE_BUILD_TIMESTAMP OFF CACHE BOOL "" FORCE)
set(USE_HYPRE OFF CACHE BOOL "" FORCE)
set(USE_AMGX OFF CACHE BOOL "" FORCE)
set(SILENCE_CROSSMODULE_WARNINGS ON CACHE BOOL "" FORCE)

# Use sequential dune
list(APPEND CMAKE_PREFIX_PATH /dune/serial)

# Disable packages
set(CMAKE_DISABLE_FIND_PACKAGE_CUDA ON)
set(CMAKE_DISABLE_FIND_PACKAGE_CUDAToolkit ON)
set(CMAKE_DISABLE_FIND_PACKAGE_amgcl ON)
set(CMAKE_DISABLE_FIND_PACKAGE_OpenCL ON)
set(CMAKE_DISABLE_FIND_PACKAGE_MPI ON)
set(CMAKE_DISABLE_FIND_PACKAGE_Doxygen ON)
set(CMAKE_DISABLE_FIND_PACKAGE_dune-polygongrid ON)
set(CMAKE_DISABLE_FIND_PACKAGE_rocalution ON)
set(CMAKE_DISABLE_FIND_PACKAGE_rocblas ON)
set(CMAKE_DISABLE_FIND_PACKAGE_rocsparse ON)
set(CMAKE_DISABLE_FIND_PACKAGE_Tracy ON)
set(CMAKE_DISABLE_FIND_PACKAGE_Valgrind ON)
set(CMAKE_DISABLE_FIND_PACKAGE_ParMETIS ON)
